[package]
name = "python_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.18.3", features = ["extension-module"] }
postflop-solver = { path = ".." }

[lib]
path = "lib.rs"
